services:
  master:
    image: master
    container_name: master
    environment:
      - WORKER_URLS=http://host.docker.internal:8001,http://host.docker.internal:8002
    ports:
      - "8080:8000"
  worker-1:
    image: worker
    container_name: worker-1
    ports:
      - "8001:8000"
    deploy:
      resources:
        limits:
            cpus: '1'
            memory: 512m

  worker-2:
    image: worker
    container_name: worker-2
    ports:
      - "8002:8000"
    deploy:
      resources:
        limits:
            cpus: '1'
            memory: 512m